repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3

-   repo: local
    hooks:
    -   id: run-tests-lib
        name: Run Tests in jb-lib
        entry: bash -c 'cd jb-lib && poetry run pytest'
        language: system
        types: [python]